version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: mendes
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d # Mount the initialization scripts

volumes:
  postgres_data:
